#!/usr/bin/env python3
"""Render README.md, tables/*.md and index.json from data/*.jsonl.

The tables in README.md are a PURE FUNCTION of the data files. There is no path by
which a table can contain a number that is not in a row, and `--check` fails if the
committed README differs from what the data renders. A PR that edits a table without
editing a row fails; a PR that edits a row without re-rendering fails.

Grouping is by comparability.key -- never by anything a human chose. Each table's
caption spells the key out in English and states what the group is NOT comparable to.

  python3 tools/registry_render.py [--root DIR] [--check]

Offline, stdlib only.
"""

import argparse
import datetime
import json
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import registry_lib as L  # noqa: E402
import registry_predicate as PRED  # noqa: E402

BEGIN = "<!-- BEGIN GENERATED: tables -->"
END = "<!-- END GENERATED: tables -->"
GEN_NOTE = ("<!-- GENERATED BY tools/registry_render.py FROM data/*.jsonl -- DO NOT EDIT BY HAND.\n"
            "     Every number below is rendered from a measurement row. Edit the row, then re-render. -->")


def g(x, *path, **kw):
    default = kw.get("default")
    for p in path:
        if not isinstance(x, dict):
            return default
        x = x.get(p)
        if x is None:
            return default
    return x


def fmt(v, sig=6):
    if v is None:
        return "--"
    if isinstance(v, float):
        if v == 0:
            return "0"
        return "%.*g" % (sig, v)
    return str(v)


def fmt_pct(v):
    return "--" if v is None else "%.2f %%" % (100.0 * v)


def fmt_size(b):
    if not b:
        return "--"
    return "%.1f GB" % (b / 1e9)


def badge(m, art_owner):
    by = g(m, "provenance", "measured_by")
    if by == "self-measured":
        return "measured by us (their artifact)" if art_owner and art_owner != L.MAINTAINER \
            else "measured by us"
    who = g(m, "provenance", "measurer", "name", default="unknown")
    return "reported by %s" % who


def det_badge(m):
    d = m.get("determinism") or {}
    rc = d.get("run_count") or 0
    if d.get("identical_across_runs") is True:
        return "%d runs, bitwise identical" % rc
    if rc >= 2:
        sd = d.get("population_stddev_of_run_means")
        # A zero spread with no per-run output digest is NOT a determinism result --
        # DET-004 permits the shape precisely because equal means are not evidence.
        # Say so in the cell, or the table reads as if it were.
        if sd == 0 and d.get("evidence_kind") not in (
                "tokenwise_kld_sha256", "logits_tensor_sha256",
                "hidden_state_tensor_sha256", "sealed_tokenwise_digest"):
            return "%d runs, sd 0 (no output digest)" % rc
        return "%d runs, sd %s" % (rc, fmt(sd, 3))
    return "1 run, unevidenced"


def caption(C, key, members):
    m = C["measurements"][members[0]]
    ki = g(m, "comparability", "key_inputs", default={})
    pan = C["panels"][ki["panel_id"]]
    ref = C["references"][ki["reference_id"]]
    rart = C["artifacts"].get(ref.get("artifact_ref")) or {}
    st = pan.get("structure") or {}
    sw = st.get("scoring_window") or {}
    lines = []
    lines.append("**Panel** `%s` -- %s" % (ki["panel_id"], pan.get("name")))
    lines.append("  %s contexts x %s scored positions = **%s scored positions**, score_from %s%s"
                 % (fmt(st.get("contexts")), fmt(st.get("positions_per_context")),
                    "{:,}".format(st["scored_positions_total"]) if st.get("scored_positions_total")
                    else "undisclosed",
                    sw.get("score_from"), ", windowed" if sw.get("windowed") else ""))
    lines.append("  sealed: **%s**%s -- contamination scan: **%s**"
                 % ("yes" if pan.get("sealed") else "no",
                    (" (token digest `%s...`)" % (g(pan, "identity", "panel_token_sha256", default="")[:16])
                     if pan.get("sealed") else ""),
                    "yes, %s hits" % g(pan, "contamination", "hits", default="?")
                    if g(pan, "contamination", "checked") else "NOT RUN"))
    lines.append("**Reference (teacher)** `%s` -- %s, artifact `%s`%s"
                 % (ki["reference_id"], ref.get("reference_kind"), ref.get("artifact_ref"),
                    " @%s" % (g(rart, "huggingface", "revision") or "unpinned revision")))
    lines.append("**Metric** %s, direction %s, accumulation %s"
                 % (ki["metric_name"], ki["direction"], ki["accumulation_dtype"]))
    lines.append("**Estimation surface** stack_relation `%s`, head_policy `%s`"
                 % (ki["stack_relation"], ki["head_policy"]))
    lines.append("**Comparability key** `%s`" % key)
    return lines


def not_comparable_note(C, key, members, groups):
    """State, per group, what this table is NOT comparable to -- naming the neighbours."""
    m = C["measurements"][members[0]]
    ki = g(m, "comparability", "key_inputs", default={})
    others = []
    for k2, mem2 in groups.items():
        if k2 == key:
            continue
        m2 = C["measurements"][mem2[0]]
        # A group for a DIFFERENT MODEL is not a near neighbour. Listing it under "differs in
        # panel_id and reference_id" invites exactly the comparison it is meant to forbid: a KL
        # number is a divergence over one model's own vocabulary against that model's own
        # teacher, and there is no sense in which one model's 0.003 beats another's 0.028.
        if m2["model_ref"] != m["model_ref"]:
            continue
        ki2 = g(m2, "comparability", "key_inputs", default={})
        diff = [f for f in L.COMPARABILITY_KEY_FIELDS if ki[f] != ki2[f]]
        if len(diff) <= 2:
            others.append((k2, diff, mem2))
    out = []
    out.append("> **What this table is.** Every row here shares the comparability key above: the same tokens, "
               "the same teacher capture, the same metric and direction, the same estimator precision, the same "
               "stack relation and the same head policy. That makes them CANDIDATES for ranking -- the key is a "
               "necessary partition, not a certificate. Whether they are also like-for-like on the dimensions "
               "the key omits (lane, pipeline, scope coverage, hardware) is what the predicate line above "
               "answers.")
    out.append(">")
    out.append("> **Rank is not a verdict.** The table is sorted by fidelity alone, and fidelity buys bits: a "
               "larger, higher-bitrate quant will usually sit above a smaller one, which is not news. Read the "
               "Size and Codec columns before reading the order, and compare like against like.")
    if others:
        out.append(">")
        out.append("> **What it is NOT comparable to.** The nearest neighbouring groups differ in:")
        for k2, diff, mem2 in sorted(others, key=lambda x: len(x[1]))[:4]:
            ki2 = g(C["measurements"][mem2[0]], "comparability", "key_inputs", default={})
            bits = "; ".join("`%s` %s -> %s" % (f, ki[f], ki2[f]) for f in diff)
            out.append("> - `%s` (%d row%s): %s" % (k2, len(mem2), "" if len(mem2) == 1 else "s", bits))
        out.append("> ")
        out.append("> Those numbers are in this file, under their own headings. Quoting one under the other "
                   "heading is the mistake this layout exists to prevent: the key is a function of the panel, "
                   "the teacher, the metric, the direction and the estimator, and the validator recomputes it "
                   "from those fields rather than trusting the stamped value. What that catches is a row filed "
                   "under a key its own fields do not produce. It does not catch a number attributed to the "
                   "wrong panel in the first place -- no offline checker can. That is what the receipt digests "
                   "on every row are for.")
        out.append(">")
        out.append("> Also, and always: **every table for a different model.** A KL number is a divergence "
                   "over one model's own vocabulary against that model's own teacher. It is not a quality "
                   "score that can be carried between models.")
    else:
        out.append(">")
        out.append("> **What it is NOT comparable to.** Every other table in this file: no other group shares "
                   "this key. That includes every table for a different model -- a KL number is a divergence "
                   "over one model's own vocabulary against that model's own teacher, never a score that can "
                   "be carried between models.")
    if len(members) == 1:
        out.append(">")
        out.append("> **Single-row group.** This number has nothing in the registry to be ranked against. "
                   "It is a stated fact, not a placing.")
    return out


def elsewhere_note(C, key, rows):
    """Name, per table, every artifact in it that ALSO carries a number somewhere else.

    Cherry-picking does not need a forged row: it only needs a quoter who stops reading at
    the number that flatters them. The official FP8 release, for one, has three published
    values in this file spanning 0.0188 to 0.0281 -- a 49% range across panels, none of it
    wrong and none of it interchangeable. If a reader is going to be handed one of those
    numbers out of context, the registry should at least be the place that says out loud
    how many others there are.
    """
    spread = {}
    for mid in rows:
        aid = C["measurements"][mid]["artifact_ref"]
        for other in C["measurements"].values():
            if other["artifact_ref"] != aid or other["id"] == mid:
                continue
            if g(other, "comparability", "key") == key:
                continue
            # A withdrawn row is not one of the values a reader may be handed: counting it
            # here reported "8 values here, from 0.0011 to 0.0137234 (1148% apart)" for a
            # group whose live spread is 18%. The retraction has to reach the derived prose
            # too, or the page contradicts its own table.
            if other.get("status") in WITHDRAWN_STATUS:
                continue
            spread.setdefault(aid, []).append(other)
    if not spread:
        return []
    lines = []
    worst = 0.0
    for aid in sorted(spread, key=lambda a: C["artifacts"][a].get("name") or a):
        here = [C["measurements"][mid] for mid in rows if C["measurements"][mid]["artifact_ref"] == aid]
        vals = [x["metric"]["value"] for x in here + spread[aid] if x["metric"]["value"] is not None]
        if len(set(vals)) < 2:
            continue
        lo, hi = min(vals), max(vals)
        worst = max(worst, (hi - lo) / lo if lo else 0.0)
        lines.append("> - **%s** -- %d values here, from **%s** to **%s** nats (%.0f%% apart). "
                     "Other tables: %s."
                     % (C["artifacts"][aid].get("name"), len(vals), fmt(lo), fmt(hi),
                        100.0 * (hi - lo) / lo if lo else 0.0,
                        ", ".join("`%s`" % k for k in sorted(
                            {g(x, "comparability", "key") for x in spread[aid]}))))
    if not lines:
        return []
    head = ("> **The same artifact, measured elsewhere in this file.** %s below also %s a number in "
            "another table -- on a different panel, teacher or estimator -- and the widest of those "
            "spans %.0f%%. None of the readings is wrong and none is interchangeable with another. "
            "Quoting one of them as *the* number for the artifact, without its table, is the misuse "
            "this registry exists to make obvious."
            % ("One of the artifacts" if len(lines) == 1 else "%d of the artifacts" % len(lines),
               "carries" if len(lines) == 1 else "carry", 100.0 * worst))
    if len(lines) > 2:
        return ([head, ">",
                 "> <details><summary>the %d artifacts and their ranges</summary>" % len(lines), ">"]
                + lines + [">", "> </details>", ""])
    return [head, ">"] + lines + [""]


def lane_of(C, m):
    """Which measurement lane produced a row, as declared by its pipeline record.

    None means the pipeline does not declare one. That is NOT the same as "the sealed
    lane" and this function does not pretend otherwise: rows with no declared lane stay
    in the group's main table, which makes no claim about their lane, while a row whose
    pipeline names a non-sealed lane is tabled apart from them.
    """
    pl = C["pipelines"].get(m.get("pipeline_ref")) or {}
    return (pl.get("lane") or {}).get("name")


def attributable_of(C, m):
    """value minus the row's own named floor (comparability.bias.floor_measurement_ref).

    None when the row names no floor, or when the floor cannot be resolved. This is
    computed here, at render time, from the two rows' own metric.value -- never stored as
    a field on the row -- so there is exactly one place a reader can be shown a stale
    number: nowhere. The pairing itself is guaranteed sound by the data, not by this
    function: BIAS-002 requires the floor to share this row's comparability key, BIAS-004
    requires it to measure unquantized weights, and BIAS-006 requires it to have been
    measured on this row's own lane -- so by the time a floor_measurement_ref reaches
    here it can never be the wrong panel, the wrong kind of thing, or the wrong lane.
    """
    floor_ref = g(m, "comparability", "bias", "floor_measurement_ref")
    if not floor_ref:
        return None
    floor = C["measurements"].get(floor_ref)
    fv = g(floor, "metric", "value")
    v = m["metric"]["value"]
    if fv is None or v is None:
        return None
    return v - fv


def row_line(C, mid, ref_art, show_attributable=False):
    """One table row. Returns (is_floor, line)."""
    m = C["measurements"][mid]
    a = C["artifacts"][m["artifact_ref"]]
    art_owner = (g(a, "huggingface", "repository") or "/").split("/")[0]
    unc = m.get("uncertainty") or {}
    ci = ("[%s, %s]" % (fmt(unc.get("ci95_low")), fmt(unc.get("ci95_high")))
          if unc.get("ci95_low") is not None else "--")
    srcs = m.get("provenance", {}).get("sources", [])
    link = "--"
    for src in srcs:
        if src.get("kind") in ("hf_file", "github_file"):
            link = "[receipt](%s)" % src["uri"]
            break
    else:
        if srcs:
            link = "local receipt" if srcs[0].get("kind") == "receipt_file" else srcs[0].get("kind")
    is_floor = m["artifact_ref"] == ref_art or (
        g(m, "comparability", "bias", "floor_measurement_ref") is None
        and g(m, "comparability", "bias", "kind") == "cross_stack_capture_replay")
    name = a.get("name")
    cell = ("| **%s** _(measurement floor)_ " % name) if is_floor else ("| %s " % name)
    attributable_cell = ""
    if show_attributable:
        att = attributable_of(C, m)
        attributable_cell = "| %s " % (fmt(att) if att is not None else "--")
    line = (cell
            + "| `%s` " % (("%s @%s" % (g(a, "codec", "family"),
                                        fmt(g(a, "codec", "bits_per_weight_nominal"))))
                           if g(a, "codec", "bits_per_weight_nominal") is not None
                           else g(a, "codec", "family"))
            + "| %s " % fmt_size(g(a, "weights", "size_bytes"))
            + "| **%s** " % fmt(m["metric"]["value"])
            + attributable_cell
            + "| %s " % ci
            + "| %s " % fmt_pct(g(m, "auxiliary_metrics", "top1_agreement"))
            + "| %s " % det_badge(m)
            + "| %s " % badge(m, art_owner)
            + "| %s |" % link)
    return is_floor, line


def bias_callouts(C, rows):
    """Every biased row's bias, named. Rendering only the first row's silently dropped the
    others -- and in the GLM cross-stack group the first row is the FLOOR, so the row whose
    bias text actually matters (official FP8: "0.020615 is an UPPER BOUND, do not subtract
    and publish") was the one being discarded."""
    out, seen = [], set()
    for mid in rows:
        bias = g(C["measurements"][mid], "comparability", "bias")
        if not bias:
            continue
        sig = (bias.get("kind"), bias.get("direction"), bias.get("detail"))
        if sig in seen:
            continue
        seen.add(sig)
        art = C["artifacts"].get(C["measurements"][mid]["artifact_ref"]) or {}
        out.append("> **Bias on %s** -- %s, direction %s. %s"
                   % (art.get("name") or mid, bias["kind"], bias["direction"], bias["detail"]))
        out.append("")
    return out


def attributable_note(rows):
    """Explain the Excess-over-control column once per table, rather than trusting the
    header alone to carry it. `rows` is unused beyond confirming the caller only calls
    this when at least one row in the table actually names a floor (table_header's own
    test)."""
    return [
        "> **Excess over control (nats)** = this row's value minus its named floor's "
        "value (`comparability.bias.floor_measurement_ref`) -- the raw number with this "
        "lane's own measurement floor netted out. Until 2026-08-31 this column was named "
        "*Attributable (nats)*; the rename is peer-review P1-05, and it is a claim "
        "change, not a cosmetic one: the difference D(P||Q_quant) - D(P||Q_control) "
        "is not itself a divergence, can be negative, and isolates quantization only if "
        "the two paths differ by nothing else -- an assumption this project's own "
        "pipeline and hardware studies show is non-trivial. It is an estimate, not an "
        "identity: KL is not additive, and the subtraction is only meaningful because "
        "both terms are small and share the same reference and the same lane. Do not "
        "quote a RATIO of two of these numbers without uncertainty: a ratio of small "
        "residuals magnifies control error. A row with no floor named shows `--`, not "
        "zero: absence of a floor is not evidence the floor is zero. BIAS-002/004/006 "
        "guarantee any floor named here shares this row's comparability key, measures "
        "unquantized weights, and was measured on this row's own lane -- so this column "
        "can never mix a floor from a different panel, a different kind of thing, or a "
        "different lane into the subtraction.",
        "",
    ]


def lane_note(C, lane, rows, total):
    """What a non-sealed lane IS, from its pipeline record's own fields.

    The comparability key has seven inputs and none of them is the lane, so a streaming-lane
    row and a sealed-lane row of the same artifact land in the same group -- adjacent, sorted
    by value, differing in the fourth decimal. Read as a ranking that says the streaming K6
    beat the sealed K6, which is not a thing that happened: it is one artifact measured twice
    on two machines. So the lane's rows get their own table, and this note says what the lane
    changed, using the numbers on the pipeline record rather than adjectives.
    """
    pl = None
    for mid in rows:
        cand = C["pipelines"].get(C["measurements"][mid].get("pipeline_ref"))
        if cand and (cand.get("lane") or {}).get("name") == lane:
            pl = cand
            break
    ln = (pl or {}).get("lane") or {}
    out = ["##### Lane `%s` -- %d of this group's %d rows" % (lane, len(rows), total), ""]
    out.append("> **A different lane. Same key, and that is exactly the problem this table solves.** "
               "The comparability key is a function of the panel, the teacher, the metric, the "
               "direction, the estimator precision, the stack relation and the head policy -- and "
               "these rows match the table above on all seven. What they do not share is the machine "
               "and the code path that produced the candidate logits, and lanes are not "
               "interchangeable. Sorting them into one list would read as a ranking; where the same "
               "artifact appears in both, it is one set of weights measured twice, not two quants.")
    out.append(">")
    bits = []
    if ln.get("device_count") is not None:
        bits.append("**%d device%s**" % (ln["device_count"], "" if ln["device_count"] == 1 else "s"))
    if ln.get("expert_parallel_emulated"):
        bits.append("expert-parallel width **%s emulated in one process**"
                    % (ln.get("expert_parallel_world_size") or "?"))
    if ln.get("reduce_order"):
        bits.append("routed-expert combine order `%s`" % ln["reduce_order"])
    if bits:
        out.append("> **What the lane is** (from `%s`): %s." % (pl["id"], ", ".join(bits)))
        out.append(">")
    br = ln.get("bridge") or {}
    if br.get("delta_mean_kld") is not None:
        out.append("> **Bridge to the `%s` lane, measured on this panel:** signed delta **%s** nats "
                   "on the mean against `%s`, worst single window **%s**, over %s windows. "
                   "Tokenwise KL array matches the sealed run: **%s**. The runner's own verdict on "
                   "whether this may be published as a reproduction of the sealed number: **%s**%s."
                   % (br.get("compared_to_lane"), fmt(br["delta_mean_kld"], 5),
                      br.get("sealed_measurement_ref"), fmt(br.get("max_abs_per_window_delta"), 5),
                      fmt(br.get("windows_compared")),
                      "yes" if br.get("tokenwise_kld_sha256_matches_sealed") else "no",
                      "yes" if br.get("publishable_as_reproduction") else "no",
                      (" (verdict `%s`)" % br["verdict"]) if br.get("verdict") else ""))
        out.append(">")
        out.append("> That bridge is one artifact's, on one panel. It is not a constant and it is not "
                   "subtractable: a row in this table whose artifact has no sealed-lane row has no "
                   "measured offset at all, and says so in its own bias line.")
    else:
        out.append("> **No bridge to the sealed lane is recorded for this lane.**")
    out.append("")
    return out


WITHDRAWN_STATUS = ("superseded", "retracted")


def _live(C, mids):
    """Members whose rows are still standing. `pending` counts: it is a registered artifact
    with a null value, it renders as "--" and it sorts last."""
    return [m for m in mids
            if C["measurements"][m].get("status") not in WITHDRAWN_STATUS]


def _withdrawn(C, mids):
    return [m for m in mids if C["measurements"][m].get("status") in WITHDRAWN_STATUS]


def render_group(C, key, members, groups):
    # The renderer filtered nothing on `status`. The registry has a retraction mechanism --
    # the status enum, `supersedes`, DISC-003 -- whose result was invisible in the published
    # document: a retracted row was tabled exactly like a live one, in rank order, and the
    # word "retracted" appeared nowhere in README.md. A retracted number that still ranks
    # first is worse than no retraction at all. The counts and the derived prose below use
    # the same partition, or the page contradicts its own table.
    all_members = list(members)
    live = _live(C, members)
    members = live or members
    out = []
    out += caption(C, key, members)
    pred = PRED.group_predicate(C, all_members)
    dims_failed = sorted(d for d, v in pred["secondary"].items() if v["status"] == "fail")
    dims_unknown = sorted(d for d, v in pred["secondary"].items() if v["status"] == "unknown")
    verdict_gloss = {
        "true": "every secondary dimension (lane, pipeline, scope coverage, hardware) is "
                "recorded and homogeneous",
        "false": "a RECORDED secondary dimension differs across members: %s. Equal keys make "
                 "these rows candidates for comparison, not certified like-for-like; ranking "
                 "across the differing dimension attributes a lane/pipeline/hardware/scope "
                 "effect to quantization quality" % ", ".join(dims_failed),
        "unknown": "no recorded difference, but %s %s unrecorded for at least one member, so "
                   "homogeneity cannot be certified"
                   % (", ".join(dims_unknown), "is" if len(dims_unknown) == 1 else "are"),
    }[pred["comparable"]]
    out.append("**Like-for-like predicate** `comparable: %s` -- %s. Machine-readable form with "
               "per-dimension values: this key's `comparability` block in `index.json`."
               % (pred["comparable"], verdict_gloss))
    out.append("")
    out += not_comparable_note(C, key, members, groups)
    out.append("")
    rows = sorted(members, key=lambda mid: (
        C["measurements"][mid]["metric"]["value"] is None,
        C["measurements"][mid]["metric"]["value"] or 0.0))
    ref_art = (C["references"][C["measurements"][members[0]]["reference_ref"]] or {}).get("artifact_ref")

    primary, lanes = [], {}
    for mid in rows:
        ln = lane_of(C, C["measurements"][mid])
        if ln is None or ln == "sealed-ep8":
            primary.append(mid)
        else:
            lanes.setdefault(ln, []).append(mid)

    metric_name = C["measurements"][members[0]]["metric"]["name"]

    def table_header(mids, allow_attributable):
        # The Excess-over-control column is added ONLY to a non-sealed-LANE sub-table that has a
        # row naming a floor (comparability.bias.floor_measurement_ref); `allow_attributable`
        # is False for the primary table. This registry has an older, deliberately more
        # cautious convention for a CROSS-STACK floor -- "the naive difference is X, do not
        # subtract and publish" stays prose-only there (see the bias callouts below) -- and
        # the primary table is where every cross_stack group's rows live, since a crosscheck
        # pipeline never declares a `lane`. A same-stack LANE floor is a different case this
        # registry is choosing to formalize (engines/BF16-FLOOR.md): both terms are small, share
        # the same reference AND the same lane, and BIAS-002/004/006 guarantee the pairing is
        # sound, so the derived number earns a column instead of staying prose-only.
        show = allow_attributable and any(
            g(C["measurements"][mid], "comparability", "bias", "floor_measurement_ref")
            for mid in mids)
        cols = ["Artifact", "Codec", "Size", "%s (nats)" % metric_name]
        if show:
            cols.append("Excess over control (nats)")
        cols += ["CI95", "Top-1", "Runs", "Attribution", "Receipt"]
        right = {"Size", "%s (nats)" % metric_name, "Excess over control (nats)", "Top-1"}
        header = "| " + " | ".join(cols) + " |"
        rule = "|" + "|".join("---:" if c in right else "---" for c in cols) + "|"
        return show, header, rule

    if lanes:
        out.append("> **%d of this group's %d rows came off a different measurement lane** (%s) and are "
                   "tabled on their own below, not mixed into the ordering here. The key does not carry "
                   "the lane; this file does."
                   % (sum(len(v) for v in lanes.values()), len(rows),
                      ", ".join("`%s`" % k for k in sorted(lanes))))
        out.append("")

    if primary:
        show_att, header, rule = table_header(primary, allow_attributable=False)
        floor_rows, normal_rows = [], []
        for mid in primary:
            is_floor, line = row_line(C, mid, ref_art, show_att)
            (floor_rows if is_floor else normal_rows).append(line)
        out.append(header)
        out.append(rule)
        out += floor_rows + normal_rows
        out.append("")
        if show_att:
            out += attributable_note(primary)
        out += bias_callouts(C, primary)

    for lane in sorted(lanes):
        out += lane_note(C, lane, lanes[lane], len(rows))
        show_att, header, rule = table_header(lanes[lane], allow_attributable=True)
        out.append(header)
        out.append(rule)
        for mid in lanes[lane]:
            out.append(row_line(C, mid, ref_art, show_att)[1])
        out.append("")
        if show_att:
            out += attributable_note(lanes[lane])
        out += bias_callouts(C, lanes[lane])

    gone = _withdrawn(C, all_members)
    if gone:
        out.append("> **%d row%s in this group %s been withdrawn** and %s not ranked above. A "
                   "withdrawn row is kept here, struck through, so a reader who has already quoted "
                   "it can find out that it no longer stands."
                   % (len(gone), "" if len(gone) == 1 else "s",
                      "has" if len(gone) == 1 else "have",
                      "is" if len(gone) == 1 else "are"))
        out.append("")
        out.append("| Artifact | Status | %s (nats) | Superseded by | Why |" % metric_name)
        out.append("|---|---|---:|---|---|")
        for mid in gone:
            m = C["measurements"][mid]
            art = C["artifacts"].get(m["artifact_ref"]) or {}
            val = m["metric"]["value"]
            why = next((d.get("detail") for d in (m.get("disclosures") or [])
                        if d.get("severity") == "blocking"), None) or (m.get("notes") or "--")
            out.append("| ~~%s~~ | **%s** | ~~%s~~ | %s | %s |"
                       % (art.get("name") or m["artifact_ref"], m.get("status"),
                          ("%.7g" % val) if val is not None else "--",
                          m.get("supersedes") or "--", str(why).replace("|", "/")[:180]))
        out.append("")

    out += elsewhere_note(C, key, rows)
    notes = []
    for mid in rows:
        m = C["measurements"][mid]
        for d in m.get("disclosures", []):
            if d.get("affects_comparability") or d.get("severity") in ("caveat", "blocking"):
                notes.append("- `%s` **%s**: %s" % (mid.split("--", 1)[1], d["code"], d["detail"]))
        if m.get("notes"):
            notes.append("- `%s` note: %s" % (mid.split("--", 1)[1], m["notes"]))
    if notes:
        out.append("<details><summary>Disclosures for the rows above (%d)</summary>\n" % len(notes))
        out += notes
        out.append("\n</details>")
        out.append("")
    return out


def render(C, groups):
    out = [GEN_NOTE, ""]
    by_model = {}
    for key, members in groups.items():
        m = C["measurements"][members[0]]
        by_model.setdefault(m["model_ref"], {}).setdefault(m["panel_ref"], []).append((key, members))

    vals = [m["metric"]["value"] for m in C["measurements"].values()
            if m["metric"]["value"] is not None]
    best = min((m for m in C["measurements"].values()
                if m.get("status") == "published" and m["metric"]["value"] is not None),
               key=lambda m: m["metric"]["value"],
               default=min(C["measurements"].values(),
                           key=lambda m: m["metric"]["value"]
                           if m["metric"]["value"] is not None else 1e9))
    best_ref_art = (C["references"].get(best["reference_ref"]) or {}).get("artifact_ref")
    best_gloss = ("and it is not a quant at all -- those are unquantized weights, read by a second "
                  "engine, measuring what two engines disagree by"
                  if C["artifacts"][best["artifact_ref"]].get("kind") == "base"
                  or best["artifact_ref"] == best_ref_art else
                  "and it earns that place on its own panel, against its own teacher, not against "
                  "anything else on this page")
    out += [
        "## How to read the tables below",
        "",
        "%d tables follow, one per comparability group, across %d model%s. Three things are true of all "
        "of them, and each is a mistake somebody has already made with numbers like these:"
        % (len(groups), len(by_model), "" if len(by_model) == 1 else "s"),
        "",
        "1. **A number means nothing outside its own table.** Every table states the seven-part key its "
        "rows share. Two numbers under different keys are different quantities that happen to print in "
        "the same units.",
        "2. **The smallest number on this page is not the best quant.** Today it is %s at %s nats -- %s. "
        "Sorting this file by value and reading off the top is the single easiest way to be wrong with it."
        % (C["artifacts"][best["artifact_ref"]].get("name"), fmt(best["metric"]["value"]), best_gloss),
        "3. **Nothing here compares two models.** A KL divergence is measured over one model's own "
        "vocabulary against that model's own teacher. GLM-5.3-Flash's numbers and Qwen3.8-27B's numbers "
        "are not on a shared scale and never will be.",
        "",
        "Attribution is a column, not a footnote: *measured by us*, *measured by us (their artifact)* "
        "and *reported by <name>* are three different epistemic states and the tables never merge them.",
        "",
    ]

    for model_ref in sorted(by_model):
        mdl = C["models"][model_ref]
        out.append("## %s" % mdl["name"])
        out.append("")
        out.append("`%s` -- published by %s. Tokenizer `%s`, vocabulary %s."
                   % (model_ref, g(mdl, "publisher", "name"), g(mdl, "tokenizer", "id"),
                      g(mdl, "tokenizer", "vocab_size")))
        out.append("")
        panels = by_model[model_ref]
        for panel_ref in sorted(panels, key=lambda p: -(g(C["panels"][p], "structure",
                                                          "scored_positions_total") or 0)):
            pan = C["panels"][panel_ref]
            out.append("### Panel: %s" % pan["name"])
            out.append("")
            if pan.get("derived_from"):
                out.append("Derived from `%s` by **%s**: %s" % (
                    pan["derived_from"], g(pan, "derivation", "kind"), g(pan, "derivation", "detail")))
                out.append("")
            for d in pan.get("disclosures", []):
                if d["code"] != "record_note":
                    out.append("> **Panel disclosure -- `%s`:** %s" % (d["code"], d["detail"]))
                    out.append("")
            gs = sorted(panels[panel_ref], key=lambda kv: -len(kv[1]))
            if len(gs) > 1:
                out.append("This panel carries **%d separate comparability groups**. They are different "
                           "measurements of different things and are never merged." % len(gs))
                out.append("")
            for key, members in gs:
                out.append("#### Group `%s` -- %d row%s" % (key, len(members),
                                                            "" if len(members) == 1 else "s"))
                out.append("")
                out += render_group(C, key, members, groups)
        out.append("")

    pend = [a for a in C["artifacts"].values()
            if L.has_disclosure(a, "qualification_pending")]
    if pend:
        out.append("## Materialized, not yet measured")
        out.append("")
        out.append("These artifacts are registered but have **no measurement row at all**. An artifact "
                   "without a measurement is legal here; a measurement without a number is not. There is "
                   "no value column in this section, so there is nothing to misread.")
        out.append("")
        out.append("| Artifact | Codec | Size | Status |")
        out.append("|---|---|---|---|")
        for a in sorted(pend, key=lambda x: x["id"]):
            reason = "; ".join(d["detail"] for d in a["disclosures"]
                               if d["code"] in ("qualification_pending", "size_unverified"))
            out.append("| `%s` | `%s @%s` | %s | %s |"
                       % (a["id"], g(a, "codec", "family"), fmt(g(a, "codec", "bits_per_weight_nominal")),
                          fmt_size(g(a, "weights", "size_bytes")), reason))
        out.append("")
    return "\n".join(out)


def build_index(C, groups):
    now = datetime.datetime.now(datetime.timezone.utc).replace(microsecond=0).isoformat()
    counts = {name: len(C[name]) for name, _, _ in L.COLLECTIONS}
    ms = list(C["measurements"].values())
    counts.update({
        "measurements_self_measured": sum(1 for m in ms if g(m, "provenance", "measured_by") == "self-measured"),
        "measurements_author_reported": sum(1 for m in ms if g(m, "provenance", "measured_by") == "author-reported"),
        "measurements_third_party_reported": sum(
            1 for m in ms if g(m, "provenance", "measured_by") == "third-party-reported"),
        "measurements_strict": sum(1 for m in ms if g(m, "comparability", "class") == "strict"),
        "measurements_advisory": sum(1 for m in ms if g(m, "comparability", "class") == "advisory"),
        "measurements_independently_verified": sum(
            1 for m in ms if g(m, "provenance", "independently_verified")),
    })
    keys = []
    for key, members in sorted(groups.items()):
        m = C["measurements"][members[0]]
        ki = g(m, "comparability", "key_inputs")
        pred = PRED.group_predicate(C, members)
        keys.append({"key": key, "panel_id": ki["panel_id"], "reference_id": ki["reference_id"],
                     "metric_name": ki["metric_name"], "direction": ki["direction"],
                     "accumulation_dtype": ki["accumulation_dtype"],
                     "stack_relation": ki["stack_relation"], "head_policy": ki["head_policy"],
                     "member_count": len(members),
                     "label": "%s on %s (%s, %s)" % (ki["metric_name"], ki["panel_id"],
                                                     ki["stack_relation"], ki["head_policy"]),
                     # P1-01: the key is a NECESSARY partition, never a sufficient
                     # certificate. This predicate is the machine-readable rest of
                     # the contract; the validator recomputes it (CMP-007).
                     "comparability": pred})
    return {
        "schema_version": L.SCHEMA_VERSION, "registry_id": L.REGISTRY_ID, "generated_at": now,
        "resolver_rule": "Every *_ref is the id field of a record in the collection named by the ref's id "
                         "prefix: model--, artifact--, panel--, reference--, pipeline--, measurement--.",
        "comparability_rule": "The seven-field comparability.key is a NECESSARY partition key, not a "
                              "sufficient certificate: two measurement values with different keys are "
                              "NEVER comparable, and a table that mixes keys is malformed. Equal keys "
                              "make two rows candidates for comparison ONLY -- the key deliberately "
                              "omits measurement lane, candidate pipeline, hardware and artifact "
                              "scope, all of which this project has MEASURED moving results by more "
                              "than the gaps it publishes between quantizers. Before ranking rows as "
                              "like-for-like, a consumer must also check each group's "
                              "comparability_keys[].comparability predicate: comparable=true/false/"
                              "unknown with machine-readable reasons.",
        "comparability_predicate_rule": "Per group: comparable='true' means lane, pipeline, scope "
                                        "coverage and hardware are recorded and homogeneous across "
                                        "live members; 'false' means a recorded dimension differs "
                                        "(ranking across it attributes a lane/pipeline/hardware/"
                                        "scope effect to quantization quality); 'unknown' means no "
                                        "recorded difference but at least one dimension is "
                                        "unrecorded. Recomputed by the validator (CMP-007); a "
                                        "hand-edited predicate is rejected.",
        "collections": {name: {"file": "data/%s.jsonl" % name, "schema": "schema/%s" % sf,
                               "record_count": len(C[name]),
                               "sha256": None}
                        for name, _, sf in L.COLLECTIONS},
        "counts": counts,
        "comparability_keys": keys,
        "validator": {"tool": "tools/registry_validate.py", "invariants_file": "schema/invariants.json",
                      "last_run_at": now, "passed": True},
        "cross_refs": {"local_ai_registry": {
            "model_id": None, "model_instance_id": None,
            "url": "https://huggingface.co/datasets/0xSero/local-ai-registry",
            "match_confidence": "unverified"}},
    }


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=L.repo_root(__file__))
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()

    C = L.load_registry(os.path.join(args.root, "data"))
    groups = {}
    for mid, m in C["measurements"].items():
        groups.setdefault(g(m, "comparability", "key"), []).append(mid)

    tables = render(C, groups)
    head_path = os.path.join(args.root, "README.head.md")
    with open(head_path, encoding="utf-8") as fh:
        head = fh.read()
    if BEGIN not in head or END not in head:
        print("README.head.md is missing the %s / %s markers" % (BEGIN, END), file=sys.stderr)
        return 4
    pre, rest = head.split(BEGIN, 1)
    _, post = rest.split(END, 1)
    readme = pre + BEGIN + "\n\n" + tables + "\n" + END + post

    index = build_index(C, groups)
    for name, _, _ in L.COLLECTIONS:
        p = os.path.join(args.root, "data", name + ".jsonl")
        if os.path.exists(p):
            index["collections"][name]["sha256"] = L.sha256_file(p)
    index_txt = json.dumps(index, indent=2, ensure_ascii=False, sort_keys=True) + "\n"

    drift = []
    for path, content in ((os.path.join(args.root, "README.md"), readme),
                          (os.path.join(args.root, "index.json"), index_txt)):
        old = open(path, encoding="utf-8").read() if os.path.exists(path) else None
        if old != content:
            # index.json's generated_at always moves; compare it modulo that field.
            if path.endswith("index.json") and old:
                try:
                    a, b = json.loads(old), json.loads(content)
                    a.pop("generated_at", None), b.pop("generated_at", None)
                    a.get("validator", {}).pop("last_run_at", None)
                    b.get("validator", {}).pop("last_run_at", None)
                    if a == b:
                        continue
                except ValueError:
                    pass
            drift.append(os.path.basename(path))
            if not args.check:
                with open(path, "w", encoding="utf-8") as fh:
                    fh.write(content)
    print("rendered %d comparability groups over %d measurements"
          % (len(groups), len(C["measurements"])))
    if args.check and drift:
        print("RENDER DRIFT: %s is not what the data renders. Re-run tools/registry_render.py."
              % ", ".join(drift), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
